# Generated by Django 3.1.4 on 2021-02-01 11:55

from django.db import migrations, models
import mainsite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام و نام خانوادگی')),
                ('company', models.CharField(max_length=30, verbose_name='نام شرکت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('website_name', models.URLField(blank=True)),
                ('domain', models.CharField(error_messages={'unique': 'این دامنه قبلا توسط کاربر دیگری انتخاب شده'}, max_length=50, unique=True, verbose_name='دامنه')),
                ('logo', models.ImageField(upload_to=mainsite.models.customer_directory_path, verbose_name='لوگوی موردنظر خود را ارسال کنید')),
                ('isSSL', models.BooleanField(default=False)),
                ('hasOrder', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Customer_db',
                'ordering': ['created', 'updated'],
            },
        ),
    ]
