# Generated by Django 3.1.4 on 2021-02-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20210201_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='شماره تماس'),
            preserve_default=False,
        ),
    ]
