# Generated by Django 3.1.4 on 2021-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='company',
            field=models.CharField(blank=True, max_length=30, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(error_messages={'unique': 'این دامنه قبلا ثبت شده و قابل انتخاب نیست'}, max_length=254, unique=True, verbose_name='ایمیل'),
        ),
    ]
