# Generated by Django 3.1.4 on 2021-02-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20210216_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='domain',
            field=models.CharField(error_messages={'unique': 'این دامنه قبلا ثبت شده و قابل انتخاب نیست'}, max_length=50, unique=True, verbose_name='دامنه'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
    ]
