# Generated by Django 3.1.4 on 2021-02-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210211_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='PayId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_pays', to='sales.orders')),
            ],
            options={
                'db_table': 'pay_id',
                'ordering': ['-created'],
            },
        ),
    ]
