# Generated by Django 3.1.4 on 2021-02-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210211_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='payid',
            name='pay_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
